from typing import Literal

# Available SDKs containing code examples
LanguageType = Literal[
    ".NET",
    "Bash",
    "C++",
    "CLI",
    "Go",
    "IAMPolicyGrammar",
    "Java",
    "JavaScript",
    "Kotlin",
    "PHP",
    "PowerShell",
    "Python",
    "Ruby",
    "Rust",
    "SAP ABAP",
    "Swift",
]

# All unique AWS services with code examples
# Found from unique service_sdk_id in example_meta.json
ServiceType = Literal[
    "ACM",
    "ACM PCA",
    "API Gateway",
    "AccessAnalyzer",
    "ApiGatewayManagementApi",
    "ApiGatewayV2",
    "App Mesh",
    "AppConfig",
    "AppRunner",
    "AppStream",
    "Application Auto Scaling",
    "Application Discovery Service",
    "Athena",
    "AuditManager",
    "Auto Scaling",
    "Auto Scaling Plans",
    "Backup",
    "Batch",
    "Bedrock",
    "Bedrock Agent",
    "Bedrock Agent Runtime",
    "Bedrock Runtime",
    "Budgets",
    "Chime",
    "Cloud9",
    "CloudControl",
    "CloudFormation",
    "CloudFront",
    "CloudSearch Domain",
    "CloudTrail",
    "CloudWatch",
    "CloudWatch Events",
    "CloudWatch Logs",
    "CodeBuild",
    "CodeCommit",
    "CodeDeploy",
    "CodeGuru Reviewer",
    "CodePipeline",
    "CodeStar connections",
    "Cognito Identity",
    "Cognito Identity Provider",
    "Cognito Sync",
    "Comprehend",
    "ComprehendMedical",
    "Config Service",
    "Connect",
    "Cost Explorer",
    "Cost and Usage Report Service",
    "DAX",
    "DLM",
    "Data Pipeline",
    "DataSync",
    "Database Migration Service",
    "Detective",
    "Device Farm",
    "Direct Connect",
    "Directory Service",
    "Directory Service Data",
    "DocDB",
    "DynamoDB",
    "DynamoDB Streams",
    "EBS",
    "EC2",
    "EC2 Instance Connect",
    "ECR",
    "ECR PUBLIC",
    "ECS",
    "EFS",
    "EKS",
    "EMR",
    "EMR containers",
    "ElastiCache",
    "Elastic Beanstalk",
    "Elastic Load Balancing",
    "Elastic Load Balancing v2",
    "Elastic Transcoder",
    "Elasticsearch Service",
    "EntityResolution",
    "EventBridge",
    "FMS",
    "FSx",
    "Firehose",
    "GameLift",
    "Geo Places",
    "Glacier",
    "Global Accelerator",
    "Glue",
    "Greengrass",
    "GreengrassV2",
    "GuardDuty",
    "Health",
    "HealthLake",
    "IAM",
    "IVS RealTime",
    "Inspector",
    "Inspector2",
    "IoT",
    "IoT Data Plane",
    "IoT Events",
    "IoT Events Data",
    "IoT Jobs Data Plane",
    "IoT Wireless",
    "IoTAnalytics",
    "IoTFleetWise",
    "IoTSiteWise",
    "IoTThingsGraph",
    "IotDeviceAdvisor",
    "KMS",
    "Kafka",
    "Keyspaces",
    "Kinesis",
    "Kinesis Analytics V2",
    "LakeFormation",
    "Lambda",
    "Lex Runtime Service",
    "License Manager",
    "Lightsail",
    "Location",
    "LookoutVision",
    "Machine Learning",
    "Macie2",
    "Marketplace Agreement",
    "Marketplace Catalog",
    "MediaConnect",
    "MediaConvert",
    "MediaLive",
    "MediaPackage",
    "MediaPackage Vod",
    "MediaStore",
    "MediaStore Data",
    "MediaTailor",
    "Medical Imaging",
    "MemoryDB",
    "Migration Hub",
    "NetworkFlowMonitor",
    "NetworkManager",
    "NetworkMonitor",
    "OAM",
    "ObservabilityAdmin",
    "Omics",
    "OpenSearch",
    "OpsWorks",
    "OpsWorksCM",
    "Organizations",
    "Outposts",
    "PI",
    "PartnerCentral Selling",
    "Payment Cryptography",
    "Payment Cryptography Data",
    "Personalize",
    "Personalize Events",
    "Personalize Runtime",
    "Pinpoint",
    "Pinpoint SMS Voice",
    "Pipes",
    "Polly",
    "Pricing",
    "Proton",
    "QLDB",
    "RAM",
    "RDS",
    "RDS Data",
    "Redshift",
    "Rekognition",
    "Resource Explorer 2",
    "Resource Groups",
    "Resource Groups Tagging API",
    "RoboMaker",
    "Route 53",
    "Route 53 Domains",
    "Route53 Recovery Cluster",
    "Route53Profiles",
    "Route53Resolver",
    "S3",
    "S3 Control",
    "SES",
    "SESv2",
    "SFN",
    "SNS",
    "SQS",
    "SSM",
    "SSM Contacts",
    "SSM Incidents",
    "STS",
    "SWF",
    "SageMaker",
    "Scheduler",
    "Secrets Manager",
    "SecurityHub",
    "SecurityLake",
    "ServerlessApplicationRepository",
    "Service Catalog",
    "Service Catalog AppRegistry",
    "Service Quotas",
    "ServiceDiscovery",
    "Shield",
    "Snowball",
    "Storage Gateway",
    "Support",
    "Textract",
    "Transcribe",
    "Transcribe Streaming",
    "Translate",
    "TrustedAdvisor",
    "VPC Lattice",
    "VerifiedPermissions",
    "WAF",
    "WAF Regional",
    "WAFV2",
    "WorkDocs",
    "WorkMail",
    "WorkMailMessageFlow",
    "WorkSpaces",
    "XRay",
    "codeartifact",
    "codestar notifications",
    "fis",
    "forecast",
    "grafana",
    "imagebuilder",
    "ivs",
    "ivschat",
    "kendra",
    "signer",
    "synthetics",
]

# Main categories of examples (excluding mislabeled)
CategoryType = Literal[
    "Api",
    "IAMPolicy",
    "Scenarios",
    "Hello",
    "Basics",
]

# SDK version validation mapping (language -> sdk versions)
LANGUAGE_VERSIONS = {
    ".NET": [3],
    "Bash": [2],
    "C++": [1],
    "CLI": [2],
    "Go": [2],
    "IAMPolicyGrammar": [1],
    "Java": [1, 2],
    "JavaScript": [2, 3],
    "Kotlin": [1],
    "PHP": [3],
    "PowerShell": [4],
    "Python": [3],
    "Ruby": [3],
    "Rust": [1],
    "SAP ABAP": [1],
    "Swift": [1]}

# Type for version validation (derived from supported versions)
VersionType = Literal[1, 2, 3, 4]
